create table if not exists submissions (
  submission_id text primary key,
  created_at text not null default (datetime('now')),
  uploaded_at text,
  origin text not null check (origin in ('project_anchor', 'community_submission')),
  submitter_id text,
  ticket_id text,
  status text not null check (status in ('ticketed', 'uploaded', 'pending_verification', 'validating', 'accepted', 'rejected', 'published', 'superseded')),
  status_reason text,
  bundle_schema_version text,
  raw_bundle_sha256 text not null,
  raw_bundle_r2_key text,
  raw_bundle_size_bytes integer,
  suite_release_id text,
  suite_manifest_sha256 text,
  scorecard_id text,
  model_identity_digest text,
  model_display_name text,
  lane_id text,
  tier text,
  validator_version text,
  validator_commit text,
  validated_at text,
  projection_schema_version text,
  projection_sha256 text,
  projection_r2_key text,
  public_artifact_manifest_sha256 text,
  public_artifact_r2_key text,
  redaction_status text not null default 'not_checked' check (redaction_status in ('not_checked', 'passed', 'failed', 'public_projection_only')),
  trust_label text,
  verification_level text check (verification_level is null or verification_level in ('bundle_rescored', 'spot_reproduced')),
  publish_state text not null default 'hidden' check (publish_state in ('hidden', 'preview', 'published')),
  published_at text,
  supersedes_submission_id text references submissions(submission_id),
  idempotency_key text not null unique,
  check (idempotency_key = raw_bundle_sha256)
);

create table if not exists board_entries (
  entry_id text primary key,
  submission_id text not null references submissions(submission_id),
  board_schema_version text not null,
  published_at text,
  visibility text not null check (visibility in ('private', 'preview', 'public')),
  origin text not null,
  trust_label text not null,
  verification_level text not null,
  model_display_name text,
  model_family text,
  model_file_sha256 text,
  model_quant_label text,
  runtime_name text,
  runtime_version text,
  hardware_summary text,
  lane_id text,
  tier text,
  suite_release_id text not null,
  suite_manifest_sha256 text not null,
  scorecard_id text not null,
  coverage_profile_id text not null,
  headline_complete integer not null check (headline_complete in (0, 1)),
  headline_score real,
  partial_composite real,
  measured_headline_weight real not null,
  missing_headline_weight real not null,
  known_headline_contribution real not null,
  rank_scope text not null,
  global_rank integer,
  scope_rank integer,
  axis_scores_json text not null,
  bench_scores_json text not null,
  conformance_json text not null,
  n_scored integer not null,
  n_errors integer not null,
  warning_count integer not null,
  projection_sha256 text not null,
  bundle_sha256 text not null,
  public_artifact_manifest_sha256 text
);

create index if not exists submissions_status_idx on submissions(status);
create index if not exists submissions_publish_state_idx on submissions(publish_state);
create index if not exists board_entries_visibility_idx on board_entries(visibility);
create index if not exists board_entries_scope_rank_idx on board_entries(rank_scope, scope_rank);
