from __future__ import annotations

EXIT_COMPLETE = 0
EXIT_PREFLIGHT_FAILED = 10
EXIT_AGENTIC_SETUP_REQUIRED = 15
EXIT_ENDPOINT_FAILED = 20
EXIT_WATCHDOG_TIMEOUT = 30
EXIT_UNSAFE_RESUME = 40
EXIT_CHECKPOINT_CORRUPTION = 50
EXIT_USER_INTERRUPTED = 60
EXIT_INTERNAL_RUNNER_BUG = 70
EXIT_SUBMISSION_FAILED = 80
