from __future__ import annotations

# Aggregate AppWorld-C funnel runs into the site's experimental "Agentic" column.
#
# This is a SEPARATE, additive data read. It does NOT touch the frozen K+I board
# (cli/runs/board/board_v1.json), the scorecard, or the scoring registry, and the
# agentic ASR it emits is NOT folded into the Local Intelligence Index (0% Index
# weight — preview only). The leaderboard renders agentic.json as its own column,
# joined to each row by board slug; it never flows through build_data.py's
# composite/axes pipeline.
#
# Inputs : cli/runs/agentic/*.scored.run*.json  (schema "appworld-c-funnel-run/v1";
#          each carries report.agentic_success_rate in [0,1], report.tasks_total,
#          report.outcome_counts, report.results[]). Grouped by the run file's
#          `label` (e.g. "qwen36-27b-Q4_K_M", "gemma4-31b-Q4_K_M").
# Output : web/public/data/agentic.json  (deterministic: indent=2, sort_keys, trailing \n).
# Join   : each funnel label -> the board model slug, derived from web/public/data/
#          index.json by model family + quant (NOT blind-hardcoded — the exact slug
#          is read out of index.json; see _slug_for_label).
#
# One-command regen (run alongside / after `web/build_data.py`):
#     <cli-venv>/python web/build_agentic.py
# Optional flags: --runs <dir> (default cli/runs/agentic), --index <file>
#     (default web/public/data/index.json), --out <file>
#     (default web/public/data/agentic.json).

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Final

ROOT: Final = Path(__file__).resolve().parents[1]
DEFAULT_RUNS_DIR: Final = ROOT / "cli" / "runs" / "agentic"
DEFAULT_INDEX: Final = ROOT / "web" / "public" / "data" / "index.json"
DEFAULT_OUT: Final = ROOT / "web" / "public" / "data" / "agentic.json"

SCHEMA: Final = "localbench-agentic-column/v1"
GENERATED_NOTE: Final = (
    "Generated by web/build_agentic.py from cli/runs/agentic/*.scored.run*.json. "
    "EXPERIMENTAL preview: AppWorld-C interactive API-coding ASR, produced by a "
    "separate harness, 0% Local Intelligence Index weight, NOT part of the frozen "
    "K+I board. Re-run after new scored runs land to refresh the column."
)

# Funnel run files we aggregate: a *scored* run (not the *smoke* probes that share
# the directory). e.g. "qwen36-27b-Q4_K_M.scored.run1.json".
_RUN_GLOB: Final = "*.scored.run*.json"
# Parses "<run-index>" out of a "...scored.run<k>.json" filename, for the per-run series order.
_RUN_INDEX_RE: Final = re.compile(r"\.scored\.run(\d+)\.json$")

# The funnel `label` is "<familyword><familynum>-<size...>-<quant>", e.g.
# "qwen36-27b-Q4_K_M" or "gemma4-31b-Q4_K_M". We must join on family AND size, because
# one family (e.g. Gemma 4) has several sizes in index.json (12b/26b/31b/...). This map
# only translates the label's compact family word to the family token used in index.json
# catalog_ids; the size token and the resulting slug are read from index.json, never
# hardcoded. Extend when a new model family gets an agentic funnel.
_LABEL_FAMILY_PREFIXES: Final = {
    "qwen36": "qwen3.6",
    "gemma4": "gemma-4",
}

# Quant tokens that may trail the label; everything from the first of these onward is the
# quant, not part of the size. Order longest-first so e.g. "Q4_K_M" beats a bare "Q4".
_QUANT_TOKENS: Final = ("Q8_0", "Q6_K", "Q5_K_M", "Q5_K_S", "Q4_K_M", "Q4_K_S", "Q4_0", "Q3_K_M", "Q3_K_S", "Q2_K", "BF16", "F16", "FP8")
# Instruct/chat suffixes on an index catalog_id stem that are NOT part of the size token
# (the funnel label omits them), e.g. "gemma-4-31b-it" -> size key "31b".
_INDEX_STEM_SUFFIXES: Final = ("it", "instruct", "chat")


class AgenticBuildError(RuntimeError):
    """A funnel run or the index could not be read/joined; aborts with a clear message."""


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    try:
        payload = build_agentic(runs_dir=args.runs, index_path=args.index)
    except (AgenticBuildError, OSError, json.JSONDecodeError) as exc:
        print(f"build_agentic: {exc}", file=sys.stderr)
        return 2
    _write_json(args.out, payload)
    n = len(payload["models"])
    try:
        rel = args.out.relative_to(ROOT)
    except ValueError:
        rel = args.out
    print(f"wrote {rel} ({n} model{'s' if n != 1 else ''})")
    return 0


def build_agentic(*, runs_dir: Path, index_path: Path) -> dict[str, object]:
    """Scan the scored funnel runs, average ASR per model label across its run files,
    and join each label to its board slug. Returns the deterministic agentic.json payload."""
    slug_for_label = _slug_resolver(index_path)
    run_files = sorted(p for p in runs_dir.glob(_RUN_GLOB) if p.is_file())

    # label -> [(run_index, ASR, tasks_total, source_path)], ordered by run index then name.
    grouped: dict[str, list[tuple[int, float, int, Path]]] = {}
    for path in run_files:
        record = _read_json(path)
        label = _require_str(record.get("label"), f"{path.name}:label")
        report = _require_obj(record.get("report"), f"{path.name}:report")
        asr = _require_number(report.get("agentic_success_rate"), f"{path.name}:report.agentic_success_rate")
        if not 0.0 <= asr <= 1.0:
            raise AgenticBuildError(f"{path.name}: agentic_success_rate {asr} outside [0,1]")
        tasks_total = _require_int(report.get("tasks_total"), f"{path.name}:report.tasks_total")
        grouped.setdefault(label, []).append((_run_index(path), asr, tasks_total, path))

    # The board shows ONE row per model slug (its best variant). When a model has several quant runs
    # (a ladder) they all map to the same slug, so we must show the SAME variant the board ranks:
    # pick the label whose quant matches the row's best_run_id. Other quants stay on disk as ladder
    # data but are not shown on the row (no averaging across quants, no collision error).
    best_quant = _best_quant_by_slug(index_path)
    slug_to_labels: dict[str, list[str]] = {}
    for label in sorted(grouped):
        try:
            slug = slug_for_label(label)
        except AgenticBuildError as exc:
            # Experimental funnel runs (e.g. distills not in the catalog/index, like the
            # qwopus/qwable Qwen3.6 distills) cannot map to a board row. Skip them rather
            # than hard-failing the whole agentic preview column.
            print(f"build_agentic: skipping unmapped funnel label '{label}' ({exc})", file=sys.stderr)
            continue
        slug_to_labels.setdefault(slug, []).append(label)

    models: dict[str, object] = {}
    for slug in sorted(slug_to_labels):
        labels = slug_to_labels[slug]
        chosen = _choose_label(slug, labels, best_quant)
        if chosen is None:
            have = sorted(filter(None, (_quant_of(l) for l in labels)))
            print(
                f"build_agentic: slug '{slug}' has agentic runs for {have} but its board best-variant "
                f"is {best_quant.get(slug)!r} (not yet scored) -> column shows blank for this model",
                file=sys.stderr,
            )
            continue
        runs = sorted(grouped[chosen], key=lambda item: (item[0], item[3].name))
        asr_series = [round(asr, 6) for _, asr, _, _ in runs]
        mean_asr = sum(asr for _, asr, _, _ in runs) / len(runs)
        tasks_totals = {tasks for _, _, tasks, _ in runs}
        n_tasks = tasks_totals.pop() if len(tasks_totals) == 1 else max(tasks_totals)
        models[slug] = {
            "asr": round(mean_asr, 6),
            "asr_pct": round(mean_asr * 100.0, 2),
            "n_tasks": n_tasks,
            "n_runs": len(runs),
            "asr_series": asr_series,
            "label": chosen,
        }

    return {
        "schema": SCHEMA,
        "generated_note": GENERATED_NOTE,
        "as_of": None,
        "models": models,
    }


def _slug_resolver(index_path: Path):
    """Build a label -> slug function from index.json. We key on a canonical
    "<family-token>|<size>" join key (e.g. "gemma-4|31b", "qwen3.6|27b") harvested from each
    row's catalog_id, so a label joins to the row of the SAME family AND size (one family has
    several sizes). The resulting slug is whatever index.json calls that model — no slug
    literals live in this script."""
    index = _require_obj(_read_json(index_path), str(index_path))
    rows = index.get("models")
    if not isinstance(rows, list):
        raise AgenticBuildError(f"{index_path}: models must be a list")

    # "<family-token>|<size>" -> slug, harvested from the index rows.
    join_slug: dict[str, str] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        slug = row.get("slug")
        catalog_id = row.get("catalog_id")
        if not isinstance(slug, str) or not slug or not isinstance(catalog_id, str) or not catalog_id:
            continue
        key = _index_join_key(catalog_id)
        if key is not None:
            join_slug.setdefault(key, slug)

    def resolve(label: str) -> str:
        key = _label_join_key(label)
        slug = join_slug.get(key)
        if slug is None:
            raise AgenticBuildError(
                f"no index.json row for funnel label '{label}' (join key '{key}'); "
                f"add the family to _LABEL_FAMILY_PREFIXES or confirm the model+size is in index.json"
            )
        return slug

    return resolve


def _index_join_key(catalog_id: str) -> str | None:
    """Canonical "<family-token>|<size>" for an index catalog_id, e.g.
    'google/gemma-4-31B-it' -> 'gemma-4|31b', 'Qwen/Qwen3.6-27B' -> 'qwen3.6|27b'. The family
    token is one of _LABEL_FAMILY_PREFIXES' values; the size is the stem remainder with any
    instruct/chat suffix dropped. Returns None for stems of no mapped family (ignored)."""
    stem = catalog_id.split("/")[-1].lower()
    for family in sorted(set(_LABEL_FAMILY_PREFIXES.values()), key=len, reverse=True):
        if stem == family or stem.startswith(family + "-"):
            remainder = stem[len(family):].strip("-")
            return f"{family}|{_strip_index_suffix(remainder)}" if remainder else None
    return None


def _strip_index_suffix(size: str) -> str:
    """Drop a trailing instruct/chat suffix the funnel label omits, e.g. '31b-it' -> '31b',
    '35b-a3b' -> '35b-a3b' (no suffix). Only the LAST segment is considered a suffix."""
    parts = size.split("-")
    if len(parts) > 1 and parts[-1] in _INDEX_STEM_SUFFIXES:
        parts = parts[:-1]
    return "-".join(parts)


def _label_join_key(label: str) -> str:
    """Canonical "<family-token>|<size>" for a funnel label, e.g. 'gemma4-31b-Q4_K_M' ->
    'gemma-4|31b', 'qwen36-27b-Q4_K_M' -> 'qwen3.6|27b'. Translates the compact family word via
    _LABEL_FAMILY_PREFIXES and takes the segments between family and quant as the size."""
    segments = label.split("-")
    head = segments[0].lower()
    family = None
    for prefix in sorted(_LABEL_FAMILY_PREFIXES, key=len, reverse=True):
        if head == prefix or head.startswith(prefix):
            family = _LABEL_FAMILY_PREFIXES[prefix]
            break
    if family is None:
        raise AgenticBuildError(
            f"funnel label '{label}' has no family mapping; add its prefix to _LABEL_FAMILY_PREFIXES"
        )
    size_parts: list[str] = []
    for segment in segments[1:]:
        if segment in _QUANT_TOKENS or segment.lower() in _INDEX_STEM_SUFFIXES:
            break
        size_parts.append(segment.lower())
    if not size_parts:
        raise AgenticBuildError(f"funnel label '{label}' has no size token after the family word")
    return f"{family}|{'-'.join(size_parts)}"


def _quant_of(text: str) -> str | None:
    """The quant token embedded in a funnel label or a run_id, e.g. 'qwen36-27b-Q6_K' or
    'qwen3-6-27b__ladder-qwen36-27b-Q6_K' -> 'Q6_K'. Longest-first so 'Q4_K_M' beats a bare 'Q4'.
    None if no known quant token is present."""
    for quant in sorted(_QUANT_TOKENS, key=len, reverse=True):
        if quant in text:
            return quant
    return None


def _best_quant_by_slug(index_path: Path) -> dict[str, str]:
    """slug -> best-variant quant token, parsed from each index row's best_run_id (the board's chosen
    variant), e.g. 'qwen3-6-27b__ladder-qwen36-27b-Q6_K' -> 'Q6_K'. Rows with no parseable quant
    (e.g. catalog shells whose best_run_id is null) are omitted."""
    index = _require_obj(_read_json(index_path), str(index_path))
    rows = index.get("models")
    if not isinstance(rows, list):
        raise AgenticBuildError(f"{index_path}: models must be a list")
    out: dict[str, str] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        slug = row.get("slug")
        best_run_id = row.get("best_run_id")
        if isinstance(slug, str) and slug and isinstance(best_run_id, str) and best_run_id:
            quant = _quant_of(best_run_id)
            if quant is not None:
                out[slug] = quant
    return out


def _choose_label(slug: str, labels: list[str], best_quant: dict[str, str]) -> str | None:
    """Pick the one funnel label that represents this slug's board row. A single label is used as-is
    (the only data we have). With several (a quant ladder) pick the one matching the board
    best-variant quant; return None if that variant has not been scored yet (the column then shows
    '—' for this model until its best variant lands)."""
    if len(labels) == 1:
        return labels[0]
    want = best_quant.get(slug)
    if want is not None:
        for label in labels:
            if _quant_of(label) == want:
                return label
    return None


def _run_index(path: Path) -> int:
    match = _RUN_INDEX_RE.search(path.name)
    return int(match.group(1)) if match else 0


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Aggregate AppWorld-C funnel runs into web/public/data/agentic.json")
    parser.add_argument("--runs", type=Path, default=DEFAULT_RUNS_DIR, help="directory of *.scored.run*.json funnel runs")
    parser.add_argument("--index", type=Path, default=DEFAULT_INDEX, help="index.json to resolve board slugs from")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output agentic.json path")
    return parser.parse_args(argv)


def _read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def _require_obj(value: object, where: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise AgenticBuildError(f"{where}: expected object")
    return value


def _require_str(value: object, where: str) -> str:
    if not isinstance(value, str) or not value:
        raise AgenticBuildError(f"{where}: expected non-empty string")
    return value


def _require_number(value: object, where: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise AgenticBuildError(f"{where}: expected number")
    return float(value)


def _require_int(value: object, where: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise AgenticBuildError(f"{where}: expected integer")
    return value


if __name__ == "__main__":
    raise SystemExit(main())
