# Defaults: equal genmath/ifeval/mmlu_pro weights, seed 20260612, 10000 bootstrap iterations,
# single-stratum per-bench CIs because run JSONs lack per-item strata, and deterministic notes.

from __future__ import annotations

import importlib
import json
import re
import shutil
import sys
from pathlib import Path
from types import ModuleType
from typing import Final, NoReturn, TypeAlias

JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]
JsonObject: TypeAlias = dict[str, JsonValue]

ROOT: Final = Path(__file__).resolve().parents[1]
CLI_SRC: Final = ROOT / "cli" / "src"
BENCHES: Final = ("genmath", "ifeval", "mmlu_pro")
WEIGHTS: Final = {"genmath": 1.0, "ifeval": 1.0, "mmlu_pro": 1.0}
SEED: Final = 20260612
DEFAULT_ITERS: Final = 10_000
GENERATED_NOTE: Final = "Generated by web/build_data.py from web/data_sources.json; rerun after curation changes."


class DataBuildError(ValueError): ...


def main(argv: list[str] | None = None) -> int:
    try:
        sources, out_dir, iters = _parse_args(sys.argv[1:] if argv is None else argv)
        build_static_data(sources, out_dir, iters=iters)
    except (DataBuildError, OSError, json.JSONDecodeError) as exc:
        print(f"build_data: {exc}", file=sys.stderr)
        return 2
    print(f"wrote {out_dir.relative_to(ROOT)}")
    return 0


def build_static_data(sources_path: Path, out_dir: Path, *, iters: int = DEFAULT_ITERS) -> None:
    sources = [_source(entry, index) for index, entry in enumerate(_list(_read_json(sources_path), "data_sources"))]
    runs = [_build_run(source, order=index, iters=iters) for index, source in enumerate(sources)]
    _write_outputs(out_dir, runs)


def _build_run(source: JsonObject, *, order: int, iters: int) -> JsonObject:
    bootstrap, signed = _scoring()
    path = ROOT / _string(source["file"], "source.file")
    run = _object(_read_json(path), str(path))
    manifest = _object_or_empty(run.get("manifest"))
    suite = _object_or_empty(manifest.get("suite"))
    benches = _object(run.get("benches"), f"{path}:benches")
    items = _list(run.get("items"), f"{path}:items")
    totals = _object(run.get("totals"), f"{path}:totals")
    model_label = _model_label(source, manifest)
    family = _string(source["family"], "source.family")
    kind = _string(source["kind"], "source.kind")
    slug = _slugify(model_label)
    run_id = f"{slug}__{path.stem}"
    quant = _text(source.get("quant_label")) or _text(_object_or_empty(manifest.get("model")).get("quant_label"))
    lane = _text(source.get("reasoning_lane")) or _text(suite.get("lane"))
    correct, no_answer = _correct_lists(items)
    axes = _axes(benches, correct, no_answer, bootstrap, signed, iters)
    composite = _composite(run, correct, bootstrap, iters)
    tokens = _completion_token_stats(items)
    est_cost = _number_or_none(run.get("estimated_cost_usd"))
    summary = _manifest_summary(source, manifest, lane, quant)
    detail = {"axes": axes, "composite": composite["interval"], "data_warnings": composite["warnings"], "est_cost_usd": est_cost, "item_set_hashes": _object_or_empty(suite.get("item_set_hashes")), "kind": kind, "manifest_summary": summary, "model_label": model_label, "run_id": run_id, "suite_version": _text(suite.get("suite_version")), "tier": _text(suite.get("tier")), "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"], "totals": totals, "worst_axis": _worst_axis(axes)}
    model_row = {"axes": axes, "composite": composite["interval"], "est_cost_usd": est_cost, "hardware": _object(summary["hardware"], "summary.hardware"), "lane": lane, "n_errors": _int(totals.get("n_errors"), "totals.n_errors"), "n_items": _int(totals.get("n_items"), "totals.n_items"), "quant_label": quant, "run_id": run_id, "runtime": _object(summary["runtime"], "summary.runtime"), "tier": detail["tier"], "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"], "tok_s": _number_or_none(totals.get("completion_tokens_per_second")), "vram_footprint_gb": source["vram_footprint_gb"], "wall_time_seconds": _number_or_none(totals.get("wall_time_seconds"))}
    index_row = {"axes": axes, "best_run_id": run_id, "composite": composite["interval"], "est_cost_usd": est_cost, "family": family, "kind": kind, "lane": lane, "model_label": model_label, "n_runs": 1, "replicated": kind == "anchor", "slug": slug, "tier": detail["tier"], "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"]}
    return {"composite_raw": composite["raw_point"], "detail": detail, "family": family, "index_row": index_row, "kind": kind, "model_label": model_label, "model_row": model_row, "order": order, "run_id": run_id, "slug": slug, "suite_version": detail["suite_version"]}


def _axes(
    benches: JsonObject,
    correct: dict[str, list[bool]],
    no_answer: dict[str, int],
    bootstrap: ModuleType,
    signed: ModuleType,
    iters: int,
) -> JsonObject:
    axes: JsonObject = {}
    for bench in BENCHES:
        aggregate = _object(benches.get(bench), f"benches.{bench}")
        raw_ci = bootstrap.per_bench_ci(correct[bench], [bench] * len(correct[bench]), iters=iters, seed=SEED)
        chance = signed.chance_for_bench(bench)
        point = _number(aggregate.get("chance_corrected"), f"{bench}.chance_corrected")
        axes[bench] = _interval(point, signed.signed_score(raw_ci["lo"], chance=chance), signed.signed_score(raw_ci["hi"], chance=chance)) | {"n": _int(aggregate.get("n"), f"{bench}.n"), "n_errors": _int(aggregate.get("n_errors"), f"{bench}.n_errors"), "n_no_answer": _int(aggregate.get("n_extraction_failures"), f"{bench}.n_extraction_failures") + no_answer[bench], "raw_accuracy": _number(aggregate.get("raw_accuracy"), f"{bench}.raw_accuracy")}
    return axes


def _composite(run: JsonObject, correct: dict[str, list[bool]], bootstrap: ModuleType, iters: int) -> JsonObject:
    ci = bootstrap.composite_ci(correct, WEIGHTS, seed=SEED, iters=iters)
    stored = _number(run.get("composite"), "composite")
    warnings: list[JsonValue] = []
    if abs(ci["point"] - stored) > 1e-6:
        warnings.append(f"composite_ci point {ci['point']:.12f} differs from stored composite {stored:.12f}")
    return {"interval": _interval(stored, ci["lo"], ci["hi"]), "raw_point": stored, "warnings": warnings}


def _write_outputs(out_dir: Path, runs: list[JsonObject]) -> None:
    models_dir = out_dir / "models"
    runs_dir = out_dir / "runs"
    for generated_dir in (models_dir, runs_dir):
        if generated_dir.exists():
            shutil.rmtree(generated_dir)
        generated_dir.mkdir(parents=True, exist_ok=True)
    for run in runs:
        _write_json(runs_dir / f"{_string(run['run_id'], 'run_id')}.json", run["detail"])
    groups = _group_runs(runs)
    models: list[JsonValue] = []
    for slug in sorted(groups):
        group = groups[slug]
        best = max(group, key=lambda run: (_number(run["composite_raw"], "composite_raw"), -_int(run["order"], "order")))
        row = _object(best["index_row"], "index_row") | {
            "n_runs": len(group),
            "replicated": _string(best["kind"], "kind") == "anchor" or len(group) >= 3,
        }
        models.append(row)
        _write_json(models_dir / f"{slug}.json", {"family": best["family"], "kind": best["kind"], "model_label": best["model_label"], "runs": [run["model_row"] for run in sorted(group, key=lambda item: _int(item["order"], "order"))], "slug": slug})
    _write_json(out_dir / "index.json", {"generated_note": GENERATED_NOTE, "models": models, "suite_version": _suite_version(runs)})


def _correct_lists(items: list[JsonValue]) -> tuple[dict[str, list[bool]], dict[str, int]]:
    correct = {bench: [] for bench in BENCHES}
    no_answer = {bench: 0 for bench in BENCHES}
    for value in items:
        item = _object(value, "item")
        bench = _text(item.get("bench"))
        if bench not in correct:
            continue
        if item.get("error") is not None:
            continue
        if item.get("correct") is None:
            no_answer[bench] += 1
            continue
        correct[bench].append(_bool(item.get("correct"), f"{bench}.correct"))
    return correct, no_answer


def _manifest_summary(source: JsonObject, manifest: JsonObject, lane: str | None, quant: str | None) -> JsonObject:
    suite = _object_or_empty(manifest.get("suite"))
    sampling = _object_or_empty(manifest.get("sampling"))
    model = _object_or_empty(manifest.get("model"))
    endpoint = _object_or_empty(manifest.get("endpoint"))
    model_summary = {"family": _text(model.get("family")) or _string(source["family"], "source.family"), "file_name": _text(model.get("file_name")), "file_sha256": _text(model.get("file_sha256")), "file_size_bytes": _int_or_none(model.get("file_size_bytes")), "format": _text(model.get("format")), "runtime_reported_model": _text(endpoint.get("runtime_reported_model"))}
    return {"caps": _object_or_empty(suite.get("caps")), "hardware": _hardware(_object_or_empty(manifest.get("hardware"))), "lane": lane, "model": model_summary, "quant": quant, "runtime": _runtime(_object_or_empty(manifest.get("runtime"))), "sampling": sampling, "thinking_mode": _text(sampling.get("thinking_mode"))}


def _hardware(hardware: JsonObject) -> JsonObject:
    gpus = hardware.get("gpus") if isinstance(hardware.get("gpus"), list) else []
    gpu = _object_or_empty(gpus[0]) if gpus else {}
    vram_mb = _int_or_none(gpu.get("vram_mb"))
    gpu_summary = {"driver": _text(gpu.get("driver")), "name": _text(gpu.get("name")), "vram_gb": round(vram_mb / 1024, 1) if vram_mb is not None else None, "vram_mb": vram_mb} if gpu else None
    return {"cpu": _text(hardware.get("cpu")), "gpu": gpu_summary, "os": _text(hardware.get("os")), "ram_gb": _number_or_none(hardware.get("ram_gb"))}


def _runtime(runtime: JsonObject) -> JsonObject:
    return {"ctx_len_configured": _int_or_none(runtime.get("ctx_len_configured")), "kv_cache_quant": _text(runtime.get("kv_cache_quant")), "name": _text(runtime.get("name")), "parallel_slots": _int_or_none(runtime.get("parallel_slots")), "version": _text(runtime.get("version"))}


def _completion_token_stats(items: list[JsonValue]) -> JsonObject:
    values: list[int] = []
    for item in items:
        token = _int_or_none(_object_or_empty(_object(item, "item").get("usage")).get("completion_tokens"))
        if token is not None:
            values.append(token)
    values.sort()
    return {"median": _percentile(values, 0.5), "p95": _percentile(values, 0.95)} if values else {"median": None, "p95": None}


def _model_label(source: JsonObject, manifest: JsonObject) -> str:
    configured = _text(source.get("model_label"))
    model = _object_or_empty(manifest.get("model"))
    endpoint = _object_or_empty(manifest.get("endpoint"))
    suite = _object_or_empty(manifest.get("suite"))
    if configured:
        return configured
    if (family := _text(model.get("family"))) and (quant := _text(model.get("quant_label"))):
        return f"{family} {quant}"
    return _text(model.get("family")) or _text(endpoint.get("runtime_reported_model")) or f"{_text(endpoint.get('api_provider')) or 'unknown-provider'} {_text(suite.get('suite_version')) or 'unknown-suite'}"


def _source(value: JsonValue, index: int) -> JsonObject:
    item = _object(value, f"data_sources[{index}]")
    kind = _string(item.get("kind"), f"data_sources[{index}].kind")
    if kind not in {"anchor", "community"}:
        raise DataBuildError(f"data_sources[{index}].kind must be anchor or community")
    return {"family": _string(item.get("family"), f"data_sources[{index}].family"), "file": _string(item.get("file"), f"data_sources[{index}].file"), "kind": kind, "model_label": _string(item.get("model_label"), f"data_sources[{index}].model_label"), "notes": _nullable_text(item.get("notes"), index, "notes"), "quant_label": _nullable_text(item.get("quant_label"), index, "quant_label"), "reasoning_lane": _nullable_text(item.get("reasoning_lane"), index, "reasoning_lane"), "vram_footprint_gb": _nullable_number(item.get("vram_footprint_gb"), index, "vram_footprint_gb")}


def _parse_args(argv: list[str]) -> tuple[Path, Path, int]:
    sources = ROOT / "web" / "data_sources.json"
    out_dir = ROOT / "web" / "public" / "data"
    iters = DEFAULT_ITERS
    index = 0
    while index < len(argv):
        match argv[index]:
            case "--sources":
                sources = Path(_next_arg(argv, index)).resolve()
            case "--out":
                out_dir = Path(_next_arg(argv, index)).resolve()
            case "--iters":
                iters = _positive_int(_next_arg(argv, index), "--iters")
            case "--help" | "-h":
                print("usage: python web/build_data.py [--sources PATH] [--out PATH] [--iters N]")
                raise SystemExit(0)
            case other:
                raise DataBuildError(f"unknown argument {other}")
        index += 2
    return sources, out_dir, iters


def _scoring() -> tuple[ModuleType, ModuleType]:
    if str(CLI_SRC) not in sys.path:
        sys.path.insert(0, str(CLI_SRC))
    return importlib.import_module("localbench.scoring.bootstrap"), importlib.import_module("localbench.scoring.signed_score")


def _write_json(path: Path, payload: JsonValue) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def _read_json(path: Path) -> JsonValue:
    return json.loads(path.read_text(encoding="utf-8"))


def _interval(point: float, lo: float, hi: float) -> JsonObject:
    return {"hi": hi * 100.0, "hi_raw": hi, "lo": lo * 100.0, "lo_raw": lo, "point": point * 100.0, "point_raw": point}


def _worst_axis(axes: JsonObject) -> JsonObject:
    bench = min(BENCHES, key=lambda name: _number(_object(axes[name], name).get("point_raw"), f"{name}.point_raw"))
    axis = _object(axes[bench], bench)
    return {"bench": bench, "point": axis["point"], "point_raw": axis["point_raw"]}


def _group_runs(runs: list[JsonObject]) -> dict[str, list[JsonObject]]:
    groups: dict[str, list[JsonObject]] = {}
    for run in runs:
        groups.setdefault(_string(run["slug"], "slug"), []).append(run)
    return groups


def _suite_version(runs: list[JsonObject]) -> str | None:
    versions = sorted({_text(run.get("suite_version")) for run in runs if _text(run.get("suite_version"))})
    return versions[0] if len(versions) == 1 else "mixed" if versions else None


def _slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "model"


def _percentile(values: list[int], quantile: float) -> float:
    position = (len(values) - 1) * quantile
    lower = int(position)
    upper = min(lower + 1, len(values) - 1)
    return values[lower] * (1.0 - (position - lower)) + values[upper] * (position - lower)


def _next_arg(argv: list[str], index: int) -> str:
    return argv[index + 1] if index + 1 < len(argv) else _fail(f"{argv[index]} requires a value")


def _positive_int(value: str, context: str) -> int:
    if not value.isdecimal() or int(value) <= 0:
        _fail(f"{context} must be a positive integer")
    return int(value)


def _fail(message: str) -> NoReturn:
    raise DataBuildError(message)


def _object(value: JsonValue | None, context: str) -> JsonObject:
    return value if isinstance(value, dict) else _fail(f"{context} must be an object")


def _object_or_empty(value: JsonValue | None) -> JsonObject:
    return value if isinstance(value, dict) else {}


def _list(value: JsonValue | None, context: str) -> list[JsonValue]:
    return value if isinstance(value, list) else _fail(f"{context} must be a list")


def _string(value: JsonValue | None, context: str) -> str:
    return value if isinstance(value, str) and value else _fail(f"{context} must be a non-empty string")


def _nullable_text(value: JsonValue | None, index: int, key: str) -> str | None:
    return value if value is None or isinstance(value, str) else _fail(f"data_sources[{index}].{key} must be a string or null")


def _nullable_number(value: JsonValue | None, index: int, key: str) -> float | None:
    number = _number_or_none(value)
    if value is None or number is not None:
        return number
    raise DataBuildError(f"data_sources[{index}].{key} must be a number or null")


def _text(value: JsonValue | None) -> str | None:
    return value if isinstance(value, str) and value else None


def _number(value: JsonValue | None, context: str) -> float:
    return number if (number := _number_or_none(value)) is not None else _fail(f"{context} must be a number")


def _number_or_none(value: JsonValue | None) -> float | None:
    return None if isinstance(value, bool) else float(value) if isinstance(value, int | float) else None


def _int(value: JsonValue | None, context: str) -> int:
    return parsed if (parsed := _int_or_none(value)) is not None else _fail(f"{context} must be an integer")


def _int_or_none(value: JsonValue | None) -> int | None:
    return None if isinstance(value, bool) else int(value) if isinstance(value, int) else None


def _bool(value: JsonValue | None, context: str) -> bool:
    return value if isinstance(value, bool) else _fail(f"{context} must be a bool")


if __name__ == "__main__":
    raise SystemExit(main())
