from __future__ import annotations

import json
import math
import shutil
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Final

from build_data_args import parse_args
from build_data_axes import (
    BENCHES,
    COMPOSITE_WEIGHTS,
    build_axes,
    build_composite,
    display_item_set_hashes,
    display_sampling,
    scored_inputs,
)
from build_data_demo import build_demo_run
from build_data_catalog import (
    CATALOG_FILENAME,
    catalog_entries,
    catalog_index_row,
    catalog_key,
    catalog_model_payload,
    catalog_slug,
    run_catalog_key,
)
from build_data_support import (
    DataBuildError,
    JsonObject,
    JsonValue,
    ROOT,
    ensure_cli_src_path,
    slugify,
    bool_value as _bool,
    int_or_none as _int_or_none,
    int_value as _int,
    list_value as _list,
    nullable_number as _nullable_number,
    nullable_text as _nullable_text,
    number_or_none as _number_or_none,
    number_value as _number,
    object_or_empty as _object_or_empty,
    object_value as _object,
    string_value as _string,
    text_value as _text,
    without_scoreless_conformance_status,
)

ensure_cli_src_path()

from localbench.scoring import (  # noqa: E402
    metadata,
    worst_axis,
)
from localbench.scoring.axes import STATIC_SUITE_INDEX_VERSION, headline_web_axes, static_suite_web_weights  # noqa: E402
from localbench.scoring.scorecard import scorecard_identity  # noqa: E402

DEFAULT_ITERS: Final = 10_000
GENERATED_NOTE: Final = "Generated by web/build_data.py from web/data_sources.json and web/model_catalog.json; rerun after curation changes."
INDEX_VERSION: Final = "index-v3.0"

# The immutable scorer artifact whose Index/axis intervals the site RENDERS verbatim
# for ranked rows (see _apply_board_intervals). Path relative to the repo ROOT, like
# the other reads in this module.
BOARD_PATH: Final = ROOT / "cli" / "runs" / "board" / "board_v2.json"

# The six interval fields the site renders straight from the board for ranked rows.
_INTERVAL_FIELDS: Final = ("point", "lo", "hi", "point_raw", "lo_raw", "hi_raw")

_BOARD_AXES: Final = headline_web_axes()
_STATIC_AXES: Final = tuple(static_suite_web_weights())
_STATIC_WEIGHTS: Final = static_suite_web_weights()
_APPWORLD_C_BENCH: Final = "appworld_c"
_AGENTIC_INFRA_TIMEOUT_RATE_LIMIT: Final = 0.05
# Watchdog per_task_timeout_s=1800 as of CLI commit 5fe9186; this gate protects
# hardware-independence of the agentic axis by keeping time-starved runs unranked.
_AGENTIC_INFRA_TIMEOUT_REASON: Final = "agentic-infra-timeout-rate"


@dataclass(frozen=True, slots=True)
class BoardContext:
    headline_lane: str
    models_by_slug: dict[str, JsonObject]


@dataclass(frozen=True, slots=True)
class BuildDataFlags:
    argv: list[str]
    allow_lineage_gaps: bool


def main(argv: list[str] | None = None) -> int:
    try:
        flags = _extract_build_data_flags(sys.argv[1:] if argv is None else argv)
        sources, out_dir, iters, benches, weights = parse_args(flags.argv, root=ROOT, default_iters=DEFAULT_ITERS, default_benches=BENCHES, default_weights=COMPOSITE_WEIGHTS)
        build_static_data(sources, out_dir, iters=iters, benches=benches, weights=weights, allow_lineage_gaps=flags.allow_lineage_gaps)
    except (DataBuildError, OSError, json.JSONDecodeError) as exc:
        print(f"build_data: {exc}", file=sys.stderr)
        return 2
    print(f"wrote {_display_path(out_dir)}")
    # Refresh the EXPERIMENTAL agentic column (a separate, additive read that writes only
    # agentic.json next to the index just built). It never touches index.json/the board, so a
    # single `python web/build_data.py` keeps the agentic column current as new scored runs land.
    # Best-effort: a malformed agentic run must not fail the canonical index build.
    _build_agentic_column(out_dir)
    return 0


def _extract_build_data_flags(argv: list[str]) -> BuildDataFlags:
    filtered: list[str] = []
    allow_lineage_gaps = False
    for arg in argv:
        if arg == "--allow-lineage-gaps":
            allow_lineage_gaps = True
            continue
        filtered.append(arg)
    return BuildDataFlags(argv=filtered, allow_lineage_gaps=allow_lineage_gaps)


def _build_agentic_column(out_dir: Path) -> None:
    """Run web/build_agentic.py's aggregation against the index just written, emitting
    out_dir/agentic.json. Imported lazily and isolated in a try so it cannot affect the
    deterministic index/models/runs outputs or break the build if a run is malformed."""
    try:
        from build_agentic import DEFAULT_RUNS_DIR, build_agentic
        payload = build_agentic(runs_dir=DEFAULT_RUNS_DIR, index_path=out_dir / "index.json")
        agentic_path = out_dir / "agentic.json"
        with agentic_path.open("w", encoding="utf-8", newline="\n") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
        print(f"wrote {_display_path(agentic_path)} ({len(payload['models'])} agentic models)")
    except Exception as exc:  # noqa: BLE001 — agentic is a non-critical preview column
        print(f"build_data: agentic column skipped ({exc})", file=sys.stderr)


def build_static_data(
    sources_path: Path,
    out_dir: Path,
    *,
    iters: int = DEFAULT_ITERS,
    benches: tuple[str, ...] = BENCHES,
    weights: dict[str, float] = COMPOSITE_WEIGHTS,
    allow_lineage_gaps: bool = False,
) -> None:
    sources = [_source(entry, index) for index, entry in enumerate(_list(_read_json(sources_path), "data_sources"))]
    raw_catalog = _read_json(ROOT / "web" / CATALOG_FILENAME)
    catalog = catalog_entries(raw_catalog)
    board = _board_context()
    runs = [_build_run(source, order=index, iters=iters, benches=benches, weights=weights, board=board) for index, source in enumerate(sources)]
    _enforce_integrity_gates(
        runs,
        catalog,
        allow_lineage_gaps=allow_lineage_gaps,
        base_models_by_id=_catalog_base_models_by_id(raw_catalog),
    )
    _write_outputs(out_dir, runs, catalog)


def _board_context() -> BoardContext:
    board = _object(_read_json(BOARD_PATH), str(BOARD_PATH))
    models_by_slug = {
        slug: model
        for model in _list(board.get("models"), f"{BOARD_PATH}:models")
        for model in [_object(model, f"{BOARD_PATH}:model")]
        if (slug := _text(model.get("slug")))
    }
    return BoardContext(
        headline_lane=_string(board.get("lane_scope"), f"{BOARD_PATH}:lane_scope"),
        models_by_slug=models_by_slug,
    )


def _apply_board_intervals(slug: str, run_id: str, axes: JsonObject, composite_interval: JsonObject, board: dict[str, JsonObject]) -> None:
    """For EVERY quant run of a board-ranked model, replace the web build's RE-DERIVED composite
    and headline-axis intervals with the board's verbatim PER-SYSTEM values (matched by run_id).
    board_v2 is the single source of truth: its per-quant composites are ALL on the agentic-led
    Index scale, so stamping every system keeps the leaderboard, the landing scatter, and the
    model-page quant ladder on ONE scale. (Previously only `best_run_id` was stamped -> the best
    variant showed the agentic-led Index while sibling quants kept a re-bootstrapped K+I-only
    composite ~2x higher, so the scatter's best-variant pick diverged from the leaderboard.) Each
    system carries its OWN per-quant composite, so quants still differentiate. Mutates `axes` and
    `composite_interval` in place. No-op for unranked rows and runs with no matching board system."""
    board_model = board.get(slug)
    if board_model is None:
        return
    system = _board_system_for_run(board_model, run_id)
    if system is None:
        return
    composite_interval.update(_board_interval(_object(system.get("composite"), f"board.{slug}.system.composite")))
    board_axes = _object(system.get("axes"), f"board.{slug}.system.axes")
    for axis in _BOARD_AXES:
        if axis not in board_axes:
            continue
        board_axis = _object(board_axes[axis], f"board.{slug}.system.axes.{axis}")
        if axis in axes:
            _object(axes[axis], f"axes.{axis}").update(_board_interval(board_axis))
        else:
            # The web suite run does not compute this axis (agentic comes from the opt-in
            # AppWorld lane, NOT suite-v1), so inject the board's axis object wholesale -> it
            # renders as a first-class axis on the leaderboard, model page, and run receipt.
            axes[axis] = dict(board_axis)


def _board_conformance_gates(slug: str, run_id: str, board: dict[str, JsonObject]) -> JsonObject | None:
    board_model = board.get(slug)
    if board_model is None:
        return None
    system = _board_system_for_run(board_model, run_id)
    if system is None:
        return None
    gates = _object_or_empty(system.get("conformance_gates"))
    return dict(gates) if gates else None


def _quarantine_invalid_inline_appworld(run: JsonObject, source_benches: JsonObject, items: list[JsonValue]) -> list[JsonValue]:
    if _APPWORLD_C_BENCH not in source_benches:
        return []
    agentic_run = run.get("agentic_run")
    if _valid_inline_appworld(agentic_run):
        return []
    source_benches.pop(_APPWORLD_C_BENCH, None)
    items[:] = [
        item
        for item in items
        if not (isinstance(item, dict) and item.get("bench") == _APPWORLD_C_BENCH)
    ]
    return ["agentic appworld_c quarantined: missing diagnostics or harness-dominated client path"]


def _valid_inline_appworld(agentic_run: JsonValue | None) -> bool:
    if not isinstance(agentic_run, dict):
        return False
    diagnostics = agentic_run.get("diagnostics")
    runs = agentic_run.get("runs")
    if not isinstance(diagnostics, dict) or not isinstance(runs, list) or not runs:
        return False
    if _agentic_summary_is_harness_dominated(diagnostics):
        return False
    return not any(not isinstance(run, dict) or _agentic_summary_is_harness_dominated(run) for run in runs)


def _agentic_infra_timeout_warnings(agentic_run: JsonValue | None) -> list[JsonValue]:
    """Fail closed: an inline AppWorld record must prove healthy infrastructure rates.

    A missing, malformed, non-finite, or out-of-range ``infra_timeout_rate`` — in the
    aggregate diagnostics or in any scored run — earns the same warning as an elevated rate.
    New records also gate canonical ``infra_failure_rate`` (timeout + sandbox + transport).
    Older records without the additive canonical field retain the timeout-only gate.
    """
    if not isinstance(agentic_run, dict):
        return []
    summaries: list[JsonValue] = [agentic_run.get("diagnostics")]
    runs = agentic_run.get("runs")
    if isinstance(runs, list):
        summaries.extend(runs)
    elif runs is not None:
        return [_AGENTIC_INFRA_TIMEOUT_REASON]
    if any(not isinstance(summary, dict) or not _infra_rates_healthy(summary) for summary in summaries):
        return [_AGENTIC_INFRA_TIMEOUT_REASON]
    return []


def _infra_timeout_rate_healthy(summary: JsonObject) -> bool:
    return _rate_healthy(summary.get("infra_timeout_rate"))


def _infra_rates_healthy(summary: JsonObject) -> bool:
    if not _infra_timeout_rate_healthy(summary):
        return False
    if "infra_failure_rate" not in summary:
        # Backward compatibility is limited to genuinely older summaries. Once any additive
        # 0.3.1 transport/teardown diagnostic is present, omitting the canonical rate fails closed.
        return not any(
            field in summary
            for field in (
                "transport_failure_count",
                "transport_attempt_count",
                "transport_failure_rate",
                "teardown_failure_count",
                "teardown_failure_rate",
            )
        )
    return _rate_healthy(summary.get("infra_failure_rate"))


def _rate_healthy(value: JsonValue | None) -> bool:
    if isinstance(value, bool) or not isinstance(value, int | float):
        return False
    if not math.isfinite(value) or value < 0.0 or value > 1.0:
        return False
    return value <= _AGENTIC_INFRA_TIMEOUT_RATE_LIMIT


def _agentic_summary_is_harness_dominated(summary: JsonObject) -> bool:
    tasks_total = summary.get("tasks_total")
    tasks_succeeded = summary.get("tasks_succeeded")
    if not isinstance(tasks_total, int) or isinstance(tasks_total, bool) or tasks_total <= 0:
        return False
    if not isinstance(tasks_succeeded, int) or isinstance(tasks_succeeded, bool) or tasks_succeeded != 0:
        return False
    outcome_counts = _object_or_empty(summary.get("outcome_counts"))
    harness_terminal = sum(
        value
        for key in ("cap_exceeded", "no_final_answer", "harness_error")
        if isinstance((value := outcome_counts.get(key)), int) and not isinstance(value, bool)
    )
    return harness_terminal >= tasks_total


def _board_system_for_run(board_model: JsonObject, run_id: str) -> JsonObject | None:
    """The board model's per-quant SYSTEM row whose run_id matches this web run (else None)."""
    for system in _list(board_model.get("systems"), "board.model.systems"):
        system_obj = _object(system, "board.system")
        if _text(system_obj.get("run_id")) == run_id:
            return system_obj
    return None


def _board_interval(interval: JsonObject) -> JsonObject:
    """Just the six interval fields from a board interval object (defensive: ignore any extra
    keys an axis object carries, e.g. n/raw_accuracy, so only the bounds/point are overridden)."""
    return {field: _number(interval.get(field), f"board.interval.{field}") for field in _INTERVAL_FIELDS}


def _board_composites_for_run(
    slug: str,
    run_id: str,
    board: dict[str, JsonObject],
) -> tuple[JsonObject | None, JsonObject | None, str | None]:
    board_model = board.get(slug)
    if board_model is None:
        return None, None, None
    if _board_system_for_run(board_model, run_id) is None:
        return None, None, None
    if run_id not in {_text(board_model.get("best_run_id")), _text(board_model.get("best_system_run_id"))}:
        return None, None, None
    return (
        _board_optional_interval(board_model.get("composite_full")),
        _board_optional_interval(board_model.get("composite_static")),
        _text(board_model.get("static_index_version")),
    )


def _board_optional_interval(value: JsonValue | None) -> JsonObject | None:
    return _board_interval(value) if isinstance(value, dict) else None


def _build_run(source: JsonObject, *, order: int, iters: int, benches: tuple[str, ...], weights: dict[str, float], board: BoardContext) -> JsonObject:
    if _bool(source["demo"], "source.demo"):
        return build_demo_run(source, order=order, benches=benches, index_version=INDEX_VERSION)
    if source.get("file") is None:
        return _build_agentic_only_run(source, order=order)

    path = ROOT / _string(source["file"], "source.file")
    run = _object(_read_json(path), str(path))
    manifest = _object_or_empty(run.get("manifest"))
    suite = _object_or_empty(manifest.get("suite"))
    scorecard = _scorecard_detail(_object_or_empty(manifest.get("scorecard")))
    conformance = _object_or_empty(run.get("conformance"))
    conformance_status = _text(conformance.get("status"))
    contamination_label = _contamination_label(_text(source.get("release_date")))
    source_benches = dict(_object(run.get("benches"), f"{path}:benches"))
    items = list(_list(run.get("items"), f"{path}:items"))
    quarantined_agentic = _quarantine_invalid_inline_appworld(run, source_benches, items)
    agentic_infra_warnings = _agentic_infra_timeout_warnings(run.get("agentic_run"))
    totals = _object(run.get("totals"), f"{path}:totals")
    perf = _object_or_empty(run.get("perf"))
    model_label = _model_label(source, manifest)
    family = _string(source["family"], "source.family")
    kind = _string(source["kind"], "source.kind")
    slug = slugify(model_label)
    run_id = f"{slug}__{path.stem}"
    quant = _text(source.get("quant_label")) or _text(_object_or_empty(manifest.get("model")).get("quant_label"))
    lane = _text(source.get("reasoning_lane")) or _text(suite.get("lane"))
    values, strata, no_answer = scored_inputs(items, metadata.stratum_for_item, source_benches)
    tokens = _completion_token_stats(items)
    est_cost = _number_or_none(run.get("estimated_cost_usd"))
    tok_s = _number_or_none(totals.get("completion_tokens_per_second"))
    latency_s_median = round(tokens["median"] / tok_s, 3) if tokens["median"] is not None and tok_s and tok_s > 0 else None
    summary = _manifest_summary(source, manifest, lane, quant)
    axes, axis_warnings = build_axes(source_benches, values, strata, no_answer, iters, benches)
    composite = build_composite(run, axes, benches, weights)
    # Pure-renderer override: for EVERY quant of a board-ranked model, swap the re-bootstrapped
    # composite and headline-axis intervals for the board's verbatim per-system values (matched
    # by run_id), so the leaderboard, the landing scatter, and the model-page quant ladder all
    # render the board's single agentic-led Index scale. No-op for unranked rows / unmatched
    # runs. See _apply_board_intervals.
    composite_interval = _object(composite["interval"], "composite.interval")
    _apply_board_intervals(slug, run_id, axes, composite_interval, board.models_by_slug)
    conformance_gates = _board_conformance_gates(slug, run_id, board.models_by_slug)
    headline_complete = all(axis in axes for axis in headline_web_axes())
    static_composite = build_composite(run, axes, _STATIC_AXES, _STATIC_WEIGHTS) if _static_complete(axes) else None
    board_composite_full, board_composite_static, board_static_index_version = _board_composites_for_run(slug, run_id, board.models_by_slug)
    computed_composite_full = dict(composite_interval) if headline_complete else None
    computed_composite_static = dict(_object(static_composite["interval"], "static_composite.interval")) if static_composite is not None else None
    composite_full = board_composite_full if board_composite_full is not None else computed_composite_full
    composite_static = board_composite_static if board_composite_static is not None else computed_composite_static
    static_index_version = (board_static_index_version or STATIC_SUITE_INDEX_VERSION) if composite_static is not None else None
    annotations = _source_annotations(source, axes, headline_complete)
    tier = _text(suite.get("tier"))
    rank_eligible_before_infra = (
        tier == "standard"
        and conformance_status == "headline-comparable"
        and headline_complete
        and not quarantined_agentic
    )
    # The fail-closed infra-timeout warning decides RANKING only; it surfaces in
    # data_warnings solely for rows that were otherwise rank-eligible, so demo and
    # diagnostic rows (which often predate the field) keep clean detail pages.
    ranked = rank_eligible_before_infra and not agentic_infra_warnings
    surfaced_infra_warnings = agentic_infra_warnings if rank_eligible_before_infra else []
    score_fields = _score_fields_for_lane(lane, composite_interval, board.headline_lane)
    data_warnings = quarantined_agentic + surfaced_infra_warnings + axis_warnings + _list(composite["warnings"], "composite.warnings")
    if static_composite is not None:
        data_warnings += _list(static_composite["warnings"], "static_composite.warnings")
    detail = {"axes": axes, "composite": composite_interval, "composite_full": composite_full, "composite_static": composite_static, "data_warnings": data_warnings, "est_cost_usd": est_cost, "index_version": INDEX_VERSION, "item_set_hashes": display_item_set_hashes(_object_or_empty(suite.get("item_set_hashes"))), "kind": kind, "conformance": conformance, "contamination_label": contamination_label, "manifest_summary": summary, "model_label": model_label, "ranked": ranked, "run_id": run_id, "scorecard": scorecard, "suite_version": _text(suite.get("suite_version")), "tier": tier, "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"], "totals": totals, "worst_axis": worst_axis(axes, _headline_benches(axes, benches, weights))} | annotations
    if lane != board.headline_lane:
        detail.update(score_fields)
        detail["lane"] = lane
        detail["score_status"] = "measured"
    model_row = {"axes": axes, "composite_full": composite_full, "composite_static": composite_static, "est_cost_usd": est_cost, "file_gb": None, "hardware": _object(summary["hardware"], "summary.hardware"), "lane": lane, "n_errors": _int(totals.get("n_errors"), "totals.n_errors"), "n_items": _int(totals.get("n_items"), "totals.n_items"), "quant_label": quant, "ranked": ranked, "run_id": run_id, "runtime": _object(summary["runtime"], "summary.runtime"), "score_status": "measured", "tier": tier, "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"], "tok_s": tok_s, "latency_s_median": latency_s_median, "vram_footprint_gb": source["vram_footprint_gb"], "vram_required_gb_8k": None, "wall_time_seconds": _number_or_none(totals.get("wall_time_seconds"))} | score_fields | annotations
    index_row = {"axes": axes, "best_run_id": run_id, "gpu": _object(summary["hardware"], "summary.hardware").get("gpu"), "composite_full": composite_full, "composite_static": composite_static, "conformance_status": conformance_status, "contamination_label": contamination_label, "est_cost_usd": est_cost, "family": family, "kind": kind, "lane": lane, "latency_s_median": latency_s_median, "wall_time_seconds": _number_or_none(totals.get("wall_time_seconds")), "model_label": model_label, "n_runs": 1, "ranked": ranked, "replicated": _bool(source["independent_replication"], "source.independent_replication"), "runtime": _object(summary["runtime"], "summary.runtime"), "score_status": "measured", "slug": slug, "tier": tier, "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"]} | score_fields | annotations
    extra_status = _run_status_annotations(run, items)
    detail.update(extra_status)
    model_row.update(extra_status)
    index_row.update(extra_status)
    if static_index_version is not None:
        detail["static_index_version"] = static_index_version
        model_row["static_index_version"] = static_index_version
        index_row["static_index_version"] = static_index_version
    if conformance_gates is not None:
        detail["conformance_gates"] = conformance_gates
        model_row["conformance_gates"] = conformance_gates
        index_row["conformance_gates"] = conformance_gates
    if perf:
        detail["perf"] = perf
        model_row["perf"] = perf
    return {"catalog_id": _text(source.get("model_id")), "composite_raw": composite["raw_point"], "detail": detail, "family": family, "index_row": index_row, "kind": kind, "model_label": model_label, "model_row": model_row, "order": order, "run_id": run_id, "slug": slug, "suite_version": detail["suite_version"]}


def _build_agentic_only_run(source: JsonObject, *, order: int) -> JsonObject:
    model_label = _string(source["model_label"], "source.model_label")
    family = _string(source["family"], "source.family")
    kind = _string(source["kind"], "source.kind")
    quant = _text(source.get("quant_label"))
    lane = _text(source.get("reasoning_lane")) or "agentic-only"
    slug = slugify(model_label)
    axis = _agentic_axis(_agentic_reports(source))
    model_row = {
        "axes": {"agentic": axis},
        "composite": None,
        "est_cost_usd": None,
        "file_gb": None,
        "hardware": {"cpu": None, "gpu": None, "os": None, "ram_gb": None},
        "lane": lane,
        "n_errors": _int(axis["n_errors"], "agentic.n_errors"),
        "n_items": _int(axis["n"], "agentic.n"),
        "quant_label": quant,
        "ranked": False,
        "run_id": None,
        "runtime": {"ctx_len_configured": None, "kv_cache_quant": None, "name": None, "parallel_slots": None, "version": None},
        "score_status": "measured",
        "tier": None,
        "tokens_to_answer_median": None,
        "tokens_to_answer_p95": None,
        "tok_s": None,
        "latency_s_median": None,
        "vram_footprint_gb": source["vram_footprint_gb"],
        "vram_required_gb_8k": None,
        "wall_time_seconds": None,
    }
    index_row = {
        "axes": {"agentic": axis},
        "best_run_id": None,
        "gpu": None,
        "composite": None,
        "conformance_status": None,
        "contamination_label": _contamination_label(_text(source.get("release_date"))),
        "est_cost_usd": None,
        "family": family,
        "kind": kind,
        "lane": lane,
        "latency_s_median": None,
        "wall_time_seconds": None,
        "model_label": model_label,
        "n_runs": 1,
        "ranked": False,
        "replicated": _bool(source["independent_replication"], "source.independent_replication"),
        "score_status": "measured",
        "slug": slug,
        "tier": None,
        "tokens_to_answer_median": None,
        "tokens_to_answer_p95": None,
    }
    return {
        "catalog_id": _text(source.get("model_id")),
        "composite_raw": -1.0,
        "detail": None,
        "family": family,
        "index_row": index_row,
        "kind": kind,
        "model_label": model_label,
        "model_row": model_row,
        "order": order,
        "run_id": None,
        "slug": slug,
        "suite_version": None,
    }


def _agentic_reports(source: JsonObject) -> list[JsonObject]:
    files = source.get("agentic_file")
    paths = [files] if isinstance(files, str) else files if isinstance(files, list) else None
    if paths is None or not paths:
        raise DataBuildError("agentic-only data source requires agentic_file")
    reports: list[JsonObject] = []
    for value in paths:
        path = ROOT / _string(value, "source.agentic_file")
        run = _object(_read_json(path), str(path))
        reports.append(_object(run.get("report"), f"{path}:report"))
    return reports


def _agentic_axis(reports: list[JsonObject]) -> JsonObject:
    asrs = [_number(report.get("agentic_success_rate"), "agentic.report.agentic_success_rate") for report in reports]
    tasks = [_int(report.get("tasks_total"), "agentic.report.tasks_total") for report in reports]
    point_raw = sum(asrs) / len(asrs)
    n = max(tasks)
    return {
        "conditional_accuracy": point_raw,
        "hi": max(asrs) * 100.0,
        "hi_raw": max(asrs),
        "leaked_reasoning_rate": None,
        "lo": min(asrs) * 100.0,
        "lo_raw": min(asrs),
        "n": n,
        "n_errors": 0,
        "n_no_answer": 0,
        "no_final_answer_rate": None,
        "point": point_raw * 100.0,
        "point_raw": point_raw,
        "raw_accuracy": point_raw,
        "termination_rate": 1.0,
        "truncation_rate": None,
    }


def _headline_benches(axes: JsonObject, benches: tuple[str, ...], weights: dict[str, float]) -> tuple[str, ...]:
    """The composite-weighted (headline) axes among `benches`. The worst-axis
    companion to the composite is the weakest HEADLINE axis (METHODOLOGY-v1.2 §3),
    not the weakest of the displayed-but-unweighted experimental axes. Falls back
    to all benches if none carry weight (avoids an empty worst-axis)."""
    present = tuple(bench for bench in benches if bench in axes)
    headline = tuple(bench for bench in present if weights.get(bench, 0.0) > 0.0)
    return headline or present or benches


def _static_complete(axes: JsonObject) -> bool:
    return all(axis in axes for axis in _STATIC_AXES)


def _score_fields_for_lane(lane: str | None, composite: JsonObject, headline_lane: str) -> JsonObject:
    if lane == headline_lane:
        return {"composite": composite}
    return {"composite": None, "diagnostic_composite": composite}


def _run_status_annotations(run: JsonObject, items: list[JsonValue]) -> JsonObject:
    annotations: JsonObject = {}
    axis_status = _object_or_empty(_object_or_empty(run.get("axis_status")).get("axes"))
    if axis_status:
        annotations["axis_status"] = axis_status
    if _has_code_artifacts(items):
        annotations["has_code_artifacts"] = True
    verdict_source = _code_verdict_source(items)
    if verdict_source is not None:
        annotations["verdict_source"] = verdict_source
    return annotations


def _has_code_artifacts(items: list[JsonValue]) -> bool:
    return any(
        isinstance(item, dict)
        and item.get("bench") == "bigcodebench_hard"
        and isinstance(item.get("code_artifact"), dict)
        for item in items
    )


def _code_verdict_source(items: list[JsonValue]) -> str | None:
    sources: set[str] = set()
    for item in items:
        if not isinstance(item, dict) or item.get("bench") != "bigcodebench_hard":
            continue
        artifact = item.get("code_artifact")
        if not isinstance(artifact, dict):
            continue
        source = artifact.get("verdict_source")
        if isinstance(source, str):
            sources.add(source)
    if not sources:
        return None
    # Fail closed: a single self-reported ("submitter") coding item taints the whole row's
    # provenance, so it must win over "verifier". Otherwise a mostly-verifier run with one forged
    # "submitter" item would aggregate to "verifier" and slip past _assert_ranked_coding_provenance.
    if "submitter" in sources:
        return "submitter"
    if "verifier" in sources:
        return "verifier"
    return sorted(sources)[0]


def _source_annotations(source: JsonObject, axes: JsonObject, headline_complete: bool) -> JsonObject:
    origin = _source_origin(source)
    annotations: JsonObject = {
        "origin": origin,
        "trust_label": _text(source.get("trust_label")) or _trust_label(origin),
    }
    display_name = _text(source.get("submitter_display_name"))
    if display_name is not None:
        annotations["submitter_display_name"] = display_name
    notes = _text_list(source.get("provenance_notes"), -1, "provenance_notes")
    if notes:
        annotations["provenance_notes"] = notes
    provenance = _agentic_provenance(source, origin, headline_complete and "agentic" in axes)
    if provenance is not None:
        annotations["agentic_provenance"] = provenance
    return annotations


def _source_origin(source: JsonObject) -> str:
    origin = _text(source.get("origin"))
    if origin is not None:
        return origin
    return "project_anchor" if _text(source.get("kind")) == "anchor" else "community"


def _trust_label(origin: str) -> str:
    return "project_anchor" if origin == "project_anchor" else "community_re_scored"


def _agentic_provenance(source: JsonObject, origin: str, agentic_complete: bool) -> str | None:
    if not agentic_complete:
        return None
    annotated = _text(source.get("agentic_provenance"))
    if annotated is not None:
        return annotated
    return "project_attested" if origin == "project_anchor" else "self_reported"


# When suite-v1's frozen item subset was published/locked (suite-v1.2). A documented
# constant — NOT a suite.json field, which is hashed for suite identity (adding one would
# move the hash). Update when a new suite version freezes.
SUITE_V1_PUBLISHED: Final = date(2026, 6, 19)


def _contamination_label(release_date: str | None) -> str:
    """Clean/pre-release contamination signal (oracle #3). A model released BEFORE the
    suite's frozen subset was published could not have been tuned to game THIS leaderboard.
    (It could still be contaminated on the underlying PUBLIC benchmarks — this badge is about
    OUR frozen subset, not general benchmark hygiene.) Unknown/unparseable date -> unverified."""
    if not release_date:
        return "unverified"
    try:
        released = date.fromisoformat(release_date)
    except ValueError:
        return "unverified"
    return "pre-suite-publication" if released < SUITE_V1_PUBLISHED else "post-suite-publication"


def _scorecard_detail(scorecard: JsonObject) -> JsonObject:
    """Surface the run's frozen scoring identity and whether the site is currently
    reinterpreting it (oracle finding #1: historical reinterpretation must be visible,
    never silent). `drift` is True when ANY scoring component differs from the live
    scorecard (weights, scorers, CI method, version); `registry_drift` is the narrower
    weights-differ case that means the DISPLAYED composite is a re-score of this run.
    A null `id` = a pre-scorecard run (provenance unknown)."""
    execution_profile_id = _text(scorecard.get("execution_profile_id"))
    try:
        current = scorecard_identity(execution_profile_id)
    except ValueError:
        current = scorecard_identity()
    recorded_id = _text(scorecard.get("scorecard_id"))
    recorded_registry = _text(scorecard.get("registry_digest"))
    return {
        "id": recorded_id,
        "version": _text(scorecard.get("scorecard_version")),
        "execution_profile_id": execution_profile_id,
        "registry_digest": recorded_registry,
        "current_id": _text(current["scorecard_id"]),
        "current_registry_digest": _text(current["registry_digest"]),
        "drift": bool(recorded_id) and recorded_id != current["scorecard_id"],
        "registry_drift": bool(recorded_registry) and recorded_registry != current["registry_digest"],
    }


def _representative_run(group: list[JsonObject]) -> JsonObject:
    # Ranked (full-index, headline-scope) runs always represent the model entity: a
    # renormalized partial composite can be numerically larger than a full five-axis
    # composite, but partial diagnostics must never outrank or re-badge the model row.
    return max(
        group,
        key=lambda run: (
            bool(_object(run["index_row"], "index_row").get("ranked")),
            _number(run["composite_raw"], "composite_raw"),
            -_int(run["order"], "order"),
        ),
    )


def _assert_ranked_coding_provenance(runs: list[JsonObject]) -> None:
    """Enforce "community/self-reported coding never ranks" IN CODE (was manual-commit discipline).

    The ranked gate (_build_run) keys only on tier / conformance / headline-completeness and never
    on coding provenance, and the in-process coding sentinel is FORGEABLE (a submitter can forge a
    passing BigCodeBench verdict — docs/reports/coding-exec-framewalk-forgery-2026-07-07.md). So
    nothing structurally stops a self-reported coding run — if one were curated into
    data_sources.json, or a future path wired community submissions into the board build — from
    ranking with a forged coding score counted. This guard makes that a build-time failure.

    Invariant: any ranked row whose COMPOSITE INCLUDES THE CODING AXIS must have MAINTAINER-attested
    provenance — trust_label == "project_anchor" (a maintainer-controlled data_sources.json field)
    AND verdict_source == "verifier" (coding re-executed under the maintainer sandbox verifier). The
    submitter-controlled verdict_source string alone is NOT trusted; trust_label is the anchor.

    Keyed on the scored coding AXIS, not on has_code_artifacts: the coding score derives from bench
    aggregates / per-item correctness (build_data_axes.py), independent of any code_artifact, so a
    forged run can score the coding axis while carrying NO code_artifact (has_code_artifacts would
    stay false and an artifact-keyed guard would skip it). verdict_source is None when there is no
    code_artifact, so such a forged row fails the "== verifier" check here.
    """
    for run in runs:
        index_row = _object(run["index_row"], "index_row")
        if not index_row.get("ranked"):
            continue
        if "coding" not in _object_or_empty(index_row.get("axes")):
            continue  # coding axis not scored into this ranked row -> nothing to gate
        trust_label = index_row.get("trust_label")
        verdict_source = index_row.get("verdict_source")
        if trust_label != "project_anchor" or verdict_source != "verifier":
            raise DataBuildError(
                f"REFUSING to rank {run.get('run_id')!r}: the coding axis is present but its provenance "
                f"is not maintainer-verified (trust_label={trust_label!r}, verdict_source={verdict_source!r}). "
                f"A self-reported / community coding verdict must never produce a ranked row — the in-process "
                f"coding sentinel is forgeable (see docs/reports/coding-exec-framewalk-forgery-2026-07-07.md). "
                f"Re-execute the coding under the maintainer sandbox verifier and curate the source as "
                f"project_anchor, or leave the row unranked."
            )


def _enforce_integrity_gates(
    runs: list[JsonObject],
    catalog: list[JsonObject],
    *,
    allow_lineage_gaps: bool,
    base_models_by_id: dict[str, list[str]] | None = None,
) -> None:
    by_id = {catalog_key(entry): entry for entry in catalog}
    by_slug = {catalog_slug(entry): entry for entry in catalog}
    base_lookup = base_models_by_id or _catalog_base_models_from_entries(catalog)
    lineage_issues = _lineage_gate_issues(runs, by_id, by_slug, base_lookup)
    if lineage_issues:
        if allow_lineage_gaps:
            print("LINEAGE GATE warning (--allow-lineage-gaps):\n" + "\n".join(lineage_issues), file=sys.stderr)
        else:
            raise DataBuildError(
                "LINEAGE GATE failed:\n"
                + "\n".join(lineage_issues)
                + "\nPass --allow-lineage-gaps to downgrade this failure to a warning."
            )
    size_warnings = _size_gate_warnings(runs, by_id, by_slug)
    if size_warnings:
        print("SIZE GATE warning:\n" + "\n".join(size_warnings), file=sys.stderr)


def _lineage_gate_issues(
    runs: list[JsonObject],
    by_id: dict[str, JsonObject],
    by_slug: dict[str, JsonObject],
    base_models_by_id: dict[str, list[str]],
) -> list[str]:
    issues: list[str] = []
    for run in runs:
        if not _lineage_gated_run(run):
            continue
        entry = _catalog_entry_for_run(run, by_id, by_slug)
        slug = _string(run["slug"], "run.slug")
        run_id = _text(run.get("run_id")) or "<none>"
        if entry is None:
            issues.append(
                f"- measured row without catalog entry: slug={slug} run_id={run_id} "
                f"catalog_id={_text(run.get('catalog_id')) or '<none>'}"
            )
            continue
        issues.extend(_base_chain_issues(slug, entry, by_id, base_models_by_id))
    return issues


def _lineage_gated_run(run: JsonObject) -> bool:
    index_row = _object(run["index_row"], "run.index_row")
    return index_row.get("score_status") == "measured" and _bool(index_row.get("ranked"), "index_row.ranked")


def _catalog_entry_for_run(
    run: JsonObject,
    by_id: dict[str, JsonObject],
    by_slug: dict[str, JsonObject],
) -> JsonObject | None:
    key = run_catalog_key(run)
    if key is not None and key in by_id:
        return by_id[key]
    return by_slug.get(_string(run["slug"], "run.slug"))


def _base_chain_issues(
    slug: str,
    entry: JsonObject,
    by_id: dict[str, JsonObject],
    base_models_by_id: dict[str, list[str]],
) -> list[str]:
    model_kind = _text(entry.get("model_kind")) or "base"
    if model_kind == "base":
        return []
    catalog_id = _string(entry["id"], "catalog.id")
    bases = base_models_by_id.get(catalog_id.lower(), _base_model_values(entry.get("base_model")))
    if not bases:
        return [f"- base-chain-missing: slug={slug} catalog_id={catalog_id} base_model=<missing> missing=<missing>"]
    issues: list[str] = []
    for base_model in bases:
        missing = _missing_base_in_chain(base_model, by_id, base_models_by_id, visited={catalog_id.lower()})
        if missing is not None:
            issues.append(
                f"- base-chain-missing: slug={slug} catalog_id={catalog_id} "
                f"base_model={base_model} missing={missing}"
            )
    return issues


def _missing_base_in_chain(
    base_model: str,
    by_id: dict[str, JsonObject],
    base_models_by_id: dict[str, list[str]],
    *,
    visited: set[str],
) -> str | None:
    key = base_model.lower()
    entry = by_id.get(key)
    if entry is None:
        return base_model
    if key in visited:
        return None
    visited.add(key)
    for parent in base_models_by_id.get(key, _base_model_values(entry.get("base_model"))):
        missing = _missing_base_in_chain(parent, by_id, base_models_by_id, visited=visited)
        if missing is not None:
            return missing
    return None


def _size_gate_warnings(
    runs: list[JsonObject],
    by_id: dict[str, JsonObject],
    by_slug: dict[str, JsonObject],
) -> list[str]:
    warnings: list[str] = []
    for run in runs:
        model_row = _object(run["model_row"], "run.model_row")
        if model_row.get("score_status") != "measured":
            continue
        entry = _catalog_entry_for_run(run, by_id, by_slug)
        quant_label = _text(model_row.get("quant_label"))
        measured_gb = _number_or_none(model_row.get("vram_footprint_gb"))
        if entry is None or quant_label is None or measured_gb is None:
            continue
        catalog_gb = _catalog_file_gb(entry, quant_label)
        if catalog_gb is None or catalog_gb <= 0:
            continue
        delta = abs(measured_gb - catalog_gb) / catalog_gb
        if delta > 0.10:
            warnings.append(
                f"- slug={_string(run['slug'], 'run.slug')} run_id={_text(run.get('run_id')) or '<none>'} "
                f"quant={quant_label}: measured vram_footprint_gb={measured_gb:g} "
                "(model row vram_footprint_gb from web/data_sources.json) "
                f"vs catalog file_gb={catalog_gb:g} (web/model_catalog.json quants[].file_gb), "
                f"delta={delta * 100:.1f}%"
            )
    return warnings


def _catalog_file_gb(entry: JsonObject, quant_label: str) -> float | None:
    for quant in _list(entry.get("quants"), "catalog.quants"):
        quant_entry = _object(quant, "catalog.quant")
        if _text(quant_entry.get("label")) == quant_label:
            return _number_or_none(quant_entry.get("file_gb"))
    return None


def _catalog_base_models_by_id(raw_catalog: JsonValue) -> dict[str, list[str]]:
    raw_items = raw_catalog if isinstance(raw_catalog, list) else _list(_object(raw_catalog, "model_catalog").get("models"), "model_catalog.models")
    by_id: dict[str, list[str]] = {}
    for item in raw_items:
        entry = _object(item, "model_catalog.entry")
        model_id = _text(entry.get("id"))
        if model_id is not None:
            by_id[model_id.lower()] = _base_model_values(entry.get("base_model"))
    return by_id


def _catalog_base_models_from_entries(catalog: list[JsonObject]) -> dict[str, list[str]]:
    return {_string(entry["id"], "catalog.id").lower(): _base_model_values(entry.get("base_model")) for entry in catalog}


def _base_model_values(value: JsonValue | None) -> list[str]:
    if isinstance(value, str) and value:
        return [value]
    if isinstance(value, list):
        return [item for item in value if isinstance(item, str) and item]
    return []


def _write_outputs(out_dir: Path, runs: list[JsonObject], catalog: list[JsonObject]) -> None:
    _assert_ranked_coding_provenance(runs)  # fail before writing any output if the invariant is violated
    models_dir = out_dir / "models"
    runs_dir = out_dir / "runs"
    for generated_dir in (models_dir, runs_dir):
        if generated_dir.exists():
            shutil.rmtree(generated_dir)
        generated_dir.mkdir(parents=True, exist_ok=True)
    for run in runs:
        if run["detail"] is not None:
            _write_json(runs_dir / f"{_string(run['run_id'], 'run_id')}.json", run["detail"])
    groups = _group_runs(runs)
    catalog_run_groups = _catalog_run_groups(runs)
    catalog_slugs = {catalog_slug(entry) for entry in catalog}
    models: list[JsonValue] = []
    for entry in sorted(catalog, key=catalog_slug):
        slug = catalog_slug(entry)
        group = catalog_run_groups.get(catalog_key(entry), groups.get(slug, []))
        if group:
            best = _representative_run(group)
            row = _object(best["index_row"], "index_row") | {
                "catalog_id": entry["id"],
                "model_label": entry["display_name"],
                "n_runs": len(group),
                "replicated": any(_bool(_object(run["index_row"], "index_row").get("replicated"), "index_row.replicated") for run in group),
                "score_status": "measured",
                "slug": slug,
            }
            models.append(row)
        else:
            models.append(catalog_index_row(entry))
        _write_json(models_dir / f"{slug}.json", catalog_model_payload(entry, sorted(group, key=lambda item: _int(item["order"], "order"))))
    for slug in sorted(slug for slug in groups if slug not in catalog_slugs and not any(run_catalog_key(run) is not None for run in groups[slug])):
        group = groups[slug]
        best = _representative_run(group)
        row = _object(best["index_row"], "index_row") | {
            "n_runs": len(group),
            "replicated": any(_bool(_object(run["index_row"], "index_row").get("replicated"), "index_row.replicated") for run in group),
            "score_status": "measured",
        }
        models.append(row)
        model_payload = {"family": best["family"], "kind": best["kind"], "model_label": best["model_label"], "runs": [run["model_row"] for run in sorted(group, key=lambda item: _int(item["order"], "order"))], "slug": slug}
        if any(_bool(_object(run["model_row"], "model_row").get("demo"), "model_row.demo") for run in group if _object(run["model_row"], "model_row").get("demo") is not None):
            model_payload["demo"] = True
        _write_json(models_dir / f"{slug}.json", model_payload)
    index_models = [without_scoreless_conformance_status(_object(model, "index.model")) for model in models]
    _write_json(out_dir / "index.json", {"generated_note": GENERATED_NOTE, "index_version": INDEX_VERSION, "models": index_models, "suite_version": _suite_version(runs)})


def _manifest_summary(source: JsonObject, manifest: JsonObject, lane: str | None, quant: str | None) -> JsonObject:
    suite = _object_or_empty(manifest.get("suite"))
    sampling = _object_or_empty(manifest.get("sampling"))
    model = _object_or_empty(manifest.get("model"))
    endpoint = _object_or_empty(manifest.get("endpoint"))
    model_summary = {"family": _text(model.get("family")) or _string(source["family"], "source.family"), "file_name": _text(model.get("file_name")), "file_sha256": _text(model.get("file_sha256")), "file_size_bytes": _int_or_none(model.get("file_size_bytes")), "format": _text(model.get("format")), "runtime_reported_model": _text(endpoint.get("runtime_reported_model"))}
    return {"caps": _object_or_empty(suite.get("caps")), "hardware": _hardware(_object_or_empty(manifest.get("hardware"))), "lane": lane, "model": model_summary, "quant": quant, "runtime": _runtime(_object_or_empty(manifest.get("runtime"))), "sampling": display_sampling(sampling), "thinking_mode": _text(sampling.get("thinking_mode"))}


def _hardware(hardware: JsonObject) -> JsonObject:
    gpus = hardware.get("gpus") if isinstance(hardware.get("gpus"), list) else []
    gpu = _object_or_empty(gpus[0]) if gpus else {}
    vram_mb = _int_or_none(gpu.get("vram_mb"))
    gpu_summary = {"driver": _text(gpu.get("driver")), "name": _text(gpu.get("name")), "vram_gb": round(vram_mb / 1024, 1) if vram_mb is not None else None, "vram_mb": vram_mb} if gpu else None
    return {"cpu": _text(hardware.get("cpu")), "gpu": gpu_summary, "os": _text(hardware.get("os")), "ram_gb": _number_or_none(hardware.get("ram_gb"))}


def _runtime(runtime: JsonObject) -> JsonObject:
    return {"ctx_len_configured": _int_or_none(runtime.get("ctx_len_configured")), "kv_cache_quant": _text(runtime.get("kv_cache_quant")), "name": _text(runtime.get("name")), "parallel_slots": _int_or_none(runtime.get("parallel_slots")), "version": _text(runtime.get("version"))}


def _completion_token_stats(items: list[JsonValue]) -> JsonObject:
    values: list[int] = []
    for item in items:
        token = _int_or_none(_object_or_empty(_object(item, "item").get("usage")).get("completion_tokens"))
        if token is not None:
            values.append(token)
    values.sort()
    return {"median": _percentile(values, 0.5), "p95": _percentile(values, 0.95)} if values else {"median": None, "p95": None}


def _model_label(source: JsonObject, manifest: JsonObject) -> str:
    configured = _text(source.get("model_label"))
    model = _object_or_empty(manifest.get("model"))
    endpoint = _object_or_empty(manifest.get("endpoint"))
    suite = _object_or_empty(manifest.get("suite"))
    if configured:
        return configured
    if (family := _text(model.get("family"))) and (quant := _text(model.get("quant_label"))):
        return f"{family} {quant}"
    return _text(model.get("family")) or _text(endpoint.get("runtime_reported_model")) or f"{_text(endpoint.get('api_provider')) or 'unknown-provider'} {_text(suite.get('suite_version')) or 'unknown-suite'}"


def _source(value: JsonValue, index: int) -> JsonObject:
    item = _object(value, f"data_sources[{index}]")
    kind = _string(item.get("kind"), f"data_sources[{index}].kind")
    if kind not in {"anchor", "community"}:
        raise DataBuildError(f"data_sources[{index}].kind must be anchor or community")
    independent_replication = item.get("independent_replication")
    demo = _bool(item.get("demo"), f"data_sources[{index}].demo") if item.get("demo") is not None else False
    return {"agentic_file": item.get("agentic_file"), "agentic_provenance": _nullable_text(item.get("agentic_provenance"), index, "agentic_provenance"), "demo": demo, "demo_score": _object(item.get("demo_score"), f"data_sources[{index}].demo_score") if item.get("demo_score") is not None else None, "family": _string(item.get("family"), f"data_sources[{index}].family"), "file": _nullable_text(item.get("file"), index, "file"), "independent_replication": _bool(independent_replication, f"data_sources[{index}].independent_replication") if independent_replication is not None else False, "kind": kind, "model_id": _nullable_text(item.get("model_id"), index, "model_id"), "model_label": _string(item.get("model_label"), f"data_sources[{index}].model_label"), "notes": _nullable_text(item.get("notes"), index, "notes"), "origin": _nullable_text(item.get("origin"), index, "origin"), "provenance_notes": _text_list(item.get("provenance_notes"), index, "provenance_notes"), "quant_label": _nullable_text(item.get("quant_label"), index, "quant_label"), "reasoning_lane": _nullable_text(item.get("reasoning_lane"), index, "reasoning_lane"), "release_date": _nullable_text(item.get("release_date"), index, "release_date"), "submitter_display_name": _nullable_text(item.get("submitter_display_name"), index, "submitter_display_name"), "trust_label": _nullable_text(item.get("trust_label"), index, "trust_label"), "vram_footprint_gb": _nullable_number(item.get("vram_footprint_gb"), index, "vram_footprint_gb")}


def _text_list(value: JsonValue | None, index: int, key: str) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return list(value)
    if index < 0:
        raise DataBuildError(f"{key} must be a list of strings")
    raise DataBuildError(f"data_sources[{index}].{key} must be a list of strings")


def _write_json(path: Path, payload: JsonValue) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def _read_json(path: Path) -> JsonValue:
    return json.loads(path.read_text(encoding="utf-8"))


def _group_runs(runs: list[JsonObject]) -> dict[str, list[JsonObject]]:
    groups: dict[str, list[JsonObject]] = {}
    for run in runs:
        groups.setdefault(_string(run["slug"], "slug"), []).append(run)
    return groups


def _catalog_run_groups(runs: list[JsonObject]) -> dict[str, list[JsonObject]]:
    groups: dict[str, list[JsonObject]] = {}
    for run in runs:
        key = run_catalog_key(run)
        if key is not None:
            groups.setdefault(key, []).append(run)
    return groups


def _suite_version(runs: list[JsonObject]) -> str | None:
    versions = sorted({_text(run.get("suite_version")) for run in runs if _text(run.get("suite_version"))})
    return versions[0] if len(versions) == 1 else "mixed" if versions else None


def _percentile(values: list[int], quantile: float) -> float:
    position = (len(values) - 1) * quantile
    lower = int(position)
    upper = min(lower + 1, len(values) - 1)
    return values[lower] * (1.0 - (position - lower)) + values[upper] * (position - lower)


if __name__ == "__main__":
    raise SystemExit(main())
