from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Final

from build_data_args import parse_args
from build_data_axes import (
    BENCHES,
    COMPOSITE_WEIGHTS,
    build_axes,
    build_composite,
    display_item_set_hashes,
    display_sampling,
    scored_inputs,
)
from build_data_demo import build_demo_run
from build_data_catalog import (
    CATALOG_FILENAME,
    catalog_entries,
    catalog_index_row,
    catalog_key,
    catalog_model_payload,
    catalog_slug,
    run_catalog_key,
)
from build_data_support import (
    DataBuildError,
    JsonObject,
    JsonValue,
    ROOT,
    ensure_cli_src_path,
    slugify,
    bool_value as _bool,
    int_or_none as _int_or_none,
    int_value as _int,
    list_value as _list,
    nullable_number as _nullable_number,
    nullable_text as _nullable_text,
    number_or_none as _number_or_none,
    number_value as _number,
    object_or_empty as _object_or_empty,
    object_value as _object,
    string_value as _string,
    text_value as _text,
)

ensure_cli_src_path()

from localbench.scoring import (  # noqa: E402
    metadata,
    worst_axis,
)

DEFAULT_ITERS: Final = 10_000
GENERATED_NOTE: Final = "Generated by web/build_data.py from web/data_sources.json and web/model_catalog.json; rerun after curation changes."
INDEX_VERSION: Final = "index-v1"


def main(argv: list[str] | None = None) -> int:
    try:
        sources, out_dir, iters, benches, weights = parse_args(sys.argv[1:] if argv is None else argv, root=ROOT, default_iters=DEFAULT_ITERS, default_benches=BENCHES, default_weights=COMPOSITE_WEIGHTS)
        build_static_data(sources, out_dir, iters=iters, benches=benches, weights=weights)
    except (DataBuildError, OSError, json.JSONDecodeError) as exc:
        print(f"build_data: {exc}", file=sys.stderr)
        return 2
    print(f"wrote {out_dir.relative_to(ROOT)}")
    return 0


def build_static_data(sources_path: Path, out_dir: Path, *, iters: int = DEFAULT_ITERS, benches: tuple[str, ...] = BENCHES, weights: dict[str, float] = COMPOSITE_WEIGHTS) -> None:
    sources = [_source(entry, index) for index, entry in enumerate(_list(_read_json(sources_path), "data_sources"))]
    catalog = catalog_entries(_read_json(ROOT / "web" / CATALOG_FILENAME))
    runs = [_build_run(source, order=index, iters=iters, benches=benches, weights=weights) for index, source in enumerate(sources)]
    _write_outputs(out_dir, runs, catalog)


def _build_run(source: JsonObject, *, order: int, iters: int, benches: tuple[str, ...], weights: dict[str, float]) -> JsonObject:
    if _bool(source["demo"], "source.demo"):
        return build_demo_run(source, order=order, benches=benches, index_version=INDEX_VERSION)

    path = ROOT / _string(source["file"], "source.file")
    run = _object(_read_json(path), str(path))
    manifest = _object_or_empty(run.get("manifest"))
    suite = _object_or_empty(manifest.get("suite"))
    source_benches = _object(run.get("benches"), f"{path}:benches")
    items = _list(run.get("items"), f"{path}:items")
    totals = _object(run.get("totals"), f"{path}:totals")
    model_label = _model_label(source, manifest)
    family = _string(source["family"], "source.family")
    kind = _string(source["kind"], "source.kind")
    slug = slugify(model_label)
    run_id = f"{slug}__{path.stem}"
    quant = _text(source.get("quant_label")) or _text(_object_or_empty(manifest.get("model")).get("quant_label"))
    lane = _text(source.get("reasoning_lane")) or _text(suite.get("lane"))
    values, strata, no_answer = scored_inputs(items, metadata.stratum_for_item, source_benches)
    tokens = _completion_token_stats(items)
    est_cost = _number_or_none(run.get("estimated_cost_usd"))
    summary = _manifest_summary(source, manifest, lane, quant)
    axes, axis_warnings = build_axes(source_benches, values, strata, no_answer, iters, benches)
    composite = build_composite(run, axes, benches, weights)
    detail = {"axes": axes, "composite": composite["interval"], "data_warnings": axis_warnings + _list(composite["warnings"], "composite.warnings"), "est_cost_usd": est_cost, "index_version": INDEX_VERSION, "item_set_hashes": display_item_set_hashes(_object_or_empty(suite.get("item_set_hashes"))), "kind": kind, "manifest_summary": summary, "model_label": model_label, "run_id": run_id, "suite_version": _text(suite.get("suite_version")), "tier": _text(suite.get("tier")), "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"], "totals": totals, "worst_axis": worst_axis(axes, _headline_benches(benches, weights))}
    model_row = {"axes": axes, "composite": composite["interval"], "est_cost_usd": est_cost, "file_gb": None, "hardware": _object(summary["hardware"], "summary.hardware"), "lane": lane, "n_errors": _int(totals.get("n_errors"), "totals.n_errors"), "n_items": _int(totals.get("n_items"), "totals.n_items"), "quant_label": quant, "run_id": run_id, "runtime": _object(summary["runtime"], "summary.runtime"), "score_status": "measured", "tier": detail["tier"], "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"], "tok_s": _number_or_none(totals.get("completion_tokens_per_second")), "vram_footprint_gb": source["vram_footprint_gb"], "vram_required_gb_8k": None, "wall_time_seconds": _number_or_none(totals.get("wall_time_seconds"))}
    index_row = {"axes": axes, "best_run_id": run_id, "composite": composite["interval"], "est_cost_usd": est_cost, "family": family, "kind": kind, "lane": lane, "model_label": model_label, "n_runs": 1, "ranked": _text(detail["tier"]) == "standard", "replicated": _bool(source["independent_replication"], "source.independent_replication"), "score_status": "measured", "slug": slug, "tier": detail["tier"], "tokens_to_answer_median": tokens["median"], "tokens_to_answer_p95": tokens["p95"]}
    return {"catalog_id": _text(source.get("model_id")), "composite_raw": composite["raw_point"], "detail": detail, "family": family, "index_row": index_row, "kind": kind, "model_label": model_label, "model_row": model_row, "order": order, "run_id": run_id, "slug": slug, "suite_version": detail["suite_version"]}


def _headline_benches(benches: tuple[str, ...], weights: dict[str, float]) -> tuple[str, ...]:
    """The composite-weighted (headline) axes among `benches`. The worst-axis
    companion to the composite is the weakest HEADLINE axis (METHODOLOGY-v1.2 §3),
    not the weakest of the displayed-but-unweighted experimental axes. Falls back
    to all benches if none carry weight (avoids an empty worst-axis)."""
    headline = tuple(bench for bench in benches if weights.get(bench, 0.0) > 0.0)
    return headline or benches


def _write_outputs(out_dir: Path, runs: list[JsonObject], catalog: list[JsonObject]) -> None:
    models_dir = out_dir / "models"
    runs_dir = out_dir / "runs"
    for generated_dir in (models_dir, runs_dir):
        if generated_dir.exists():
            shutil.rmtree(generated_dir)
        generated_dir.mkdir(parents=True, exist_ok=True)
    for run in runs:
        _write_json(runs_dir / f"{_string(run['run_id'], 'run_id')}.json", run["detail"])
    groups = _group_runs(runs)
    catalog_run_groups = _catalog_run_groups(runs)
    catalog_slugs = {catalog_slug(entry) for entry in catalog}
    models: list[JsonValue] = []
    for entry in sorted(catalog, key=catalog_slug):
        slug = catalog_slug(entry)
        group = catalog_run_groups.get(catalog_key(entry), groups.get(slug, []))
        if group:
            best = max(group, key=lambda run: (_number(run["composite_raw"], "composite_raw"), -_int(run["order"], "order")))
            row = _object(best["index_row"], "index_row") | {
                "catalog_id": entry["id"],
                "model_label": entry["display_name"],
                "n_runs": len(group),
                "replicated": any(_bool(_object(run["index_row"], "index_row").get("replicated"), "index_row.replicated") for run in group),
                "score_status": "measured",
                "slug": slug,
            }
            models.append(row)
        else:
            models.append(catalog_index_row(entry))
        _write_json(models_dir / f"{slug}.json", catalog_model_payload(entry, sorted(group, key=lambda item: _int(item["order"], "order"))))
    for slug in sorted(slug for slug in groups if slug not in catalog_slugs and not any(run_catalog_key(run) is not None for run in groups[slug])):
        group = groups[slug]
        best = max(group, key=lambda run: (_number(run["composite_raw"], "composite_raw"), -_int(run["order"], "order")))
        row = _object(best["index_row"], "index_row") | {
            "n_runs": len(group),
            "replicated": any(_bool(_object(run["index_row"], "index_row").get("replicated"), "index_row.replicated") for run in group),
            "score_status": "measured",
        }
        models.append(row)
        model_payload = {"family": best["family"], "kind": best["kind"], "model_label": best["model_label"], "runs": [run["model_row"] for run in sorted(group, key=lambda item: _int(item["order"], "order"))], "slug": slug}
        if any(_bool(_object(run["model_row"], "model_row").get("demo"), "model_row.demo") for run in group if _object(run["model_row"], "model_row").get("demo") is not None):
            model_payload["demo"] = True
        _write_json(models_dir / f"{slug}.json", model_payload)
    _write_json(out_dir / "index.json", {"generated_note": GENERATED_NOTE, "index_version": INDEX_VERSION, "models": models, "suite_version": _suite_version(runs)})


def _manifest_summary(source: JsonObject, manifest: JsonObject, lane: str | None, quant: str | None) -> JsonObject:
    suite = _object_or_empty(manifest.get("suite"))
    sampling = _object_or_empty(manifest.get("sampling"))
    model = _object_or_empty(manifest.get("model"))
    endpoint = _object_or_empty(manifest.get("endpoint"))
    model_summary = {"family": _text(model.get("family")) or _string(source["family"], "source.family"), "file_name": _text(model.get("file_name")), "file_sha256": _text(model.get("file_sha256")), "file_size_bytes": _int_or_none(model.get("file_size_bytes")), "format": _text(model.get("format")), "runtime_reported_model": _text(endpoint.get("runtime_reported_model"))}
    return {"caps": _object_or_empty(suite.get("caps")), "hardware": _hardware(_object_or_empty(manifest.get("hardware"))), "lane": lane, "model": model_summary, "quant": quant, "runtime": _runtime(_object_or_empty(manifest.get("runtime"))), "sampling": display_sampling(sampling), "thinking_mode": _text(sampling.get("thinking_mode"))}


def _hardware(hardware: JsonObject) -> JsonObject:
    gpus = hardware.get("gpus") if isinstance(hardware.get("gpus"), list) else []
    gpu = _object_or_empty(gpus[0]) if gpus else {}
    vram_mb = _int_or_none(gpu.get("vram_mb"))
    gpu_summary = {"driver": _text(gpu.get("driver")), "name": _text(gpu.get("name")), "vram_gb": round(vram_mb / 1024, 1) if vram_mb is not None else None, "vram_mb": vram_mb} if gpu else None
    return {"cpu": _text(hardware.get("cpu")), "gpu": gpu_summary, "os": _text(hardware.get("os")), "ram_gb": _number_or_none(hardware.get("ram_gb"))}


def _runtime(runtime: JsonObject) -> JsonObject:
    return {"ctx_len_configured": _int_or_none(runtime.get("ctx_len_configured")), "kv_cache_quant": _text(runtime.get("kv_cache_quant")), "name": _text(runtime.get("name")), "parallel_slots": _int_or_none(runtime.get("parallel_slots")), "version": _text(runtime.get("version"))}


def _completion_token_stats(items: list[JsonValue]) -> JsonObject:
    values: list[int] = []
    for item in items:
        token = _int_or_none(_object_or_empty(_object(item, "item").get("usage")).get("completion_tokens"))
        if token is not None:
            values.append(token)
    values.sort()
    return {"median": _percentile(values, 0.5), "p95": _percentile(values, 0.95)} if values else {"median": None, "p95": None}


def _model_label(source: JsonObject, manifest: JsonObject) -> str:
    configured = _text(source.get("model_label"))
    model = _object_or_empty(manifest.get("model"))
    endpoint = _object_or_empty(manifest.get("endpoint"))
    suite = _object_or_empty(manifest.get("suite"))
    if configured:
        return configured
    if (family := _text(model.get("family"))) and (quant := _text(model.get("quant_label"))):
        return f"{family} {quant}"
    return _text(model.get("family")) or _text(endpoint.get("runtime_reported_model")) or f"{_text(endpoint.get('api_provider')) or 'unknown-provider'} {_text(suite.get('suite_version')) or 'unknown-suite'}"


def _source(value: JsonValue, index: int) -> JsonObject:
    item = _object(value, f"data_sources[{index}]")
    kind = _string(item.get("kind"), f"data_sources[{index}].kind")
    if kind not in {"anchor", "community"}:
        raise DataBuildError(f"data_sources[{index}].kind must be anchor or community")
    independent_replication = item.get("independent_replication")
    demo = _bool(item.get("demo"), f"data_sources[{index}].demo") if item.get("demo") is not None else False
    return {"demo": demo, "demo_score": _object(item.get("demo_score"), f"data_sources[{index}].demo_score") if item.get("demo_score") is not None else None, "family": _string(item.get("family"), f"data_sources[{index}].family"), "file": _string(item.get("file"), f"data_sources[{index}].file"), "independent_replication": _bool(independent_replication, f"data_sources[{index}].independent_replication") if independent_replication is not None else False, "kind": kind, "model_id": _nullable_text(item.get("model_id"), index, "model_id"), "model_label": _string(item.get("model_label"), f"data_sources[{index}].model_label"), "notes": _nullable_text(item.get("notes"), index, "notes"), "quant_label": _nullable_text(item.get("quant_label"), index, "quant_label"), "reasoning_lane": _nullable_text(item.get("reasoning_lane"), index, "reasoning_lane"), "vram_footprint_gb": _nullable_number(item.get("vram_footprint_gb"), index, "vram_footprint_gb")}


def _write_json(path: Path, payload: JsonValue) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def _read_json(path: Path) -> JsonValue:
    return json.loads(path.read_text(encoding="utf-8"))


def _group_runs(runs: list[JsonObject]) -> dict[str, list[JsonObject]]:
    groups: dict[str, list[JsonObject]] = {}
    for run in runs:
        groups.setdefault(_string(run["slug"], "slug"), []).append(run)
    return groups


def _catalog_run_groups(runs: list[JsonObject]) -> dict[str, list[JsonObject]]:
    groups: dict[str, list[JsonObject]] = {}
    for run in runs:
        key = run_catalog_key(run)
        if key is not None:
            groups.setdefault(key, []).append(run)
    return groups


def _suite_version(runs: list[JsonObject]) -> str | None:
    versions = sorted({_text(run.get("suite_version")) for run in runs if _text(run.get("suite_version"))})
    return versions[0] if len(versions) == 1 else "mixed" if versions else None


def _percentile(values: list[int], quantile: float) -> float:
    position = (len(values) - 1) * quantile
    lower = int(position)
    upper = min(lower + 1, len(values) - 1)
    return values[lower] * (1.0 - (position - lower)) + values[upper] * (position - lower)


if __name__ == "__main__":
    raise SystemExit(main())
